version: "2.1"
services:
  web:
    build:
      context: .
    volumes:
      - "<INSERT PATH HERE>:/app/out"
    ports:
      - "3366:3366"
    restart: always
    networks:
      app_net:
        ipv4_address: 172.16.238.10

networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1